default:
  image: python:3.8
  before_script:  # poetry virtual env initialization
    - pip install poetry
    - export PATH="$HOME/.local/bin:$HOME/bin:$PATH"
    - poetry install --no-ansi --no-interaction
    - source `poetry env info --path`/bin/activate

variables:
  LANG: C.UTF-8

stages:
  - test
  - linter
  - publish

pytest:
  stage: test
  script:
    - echo "This is the pytest test stage"
    - pytest --junitxml=report.xml
    artifacts:
      when: always
      reports:
        junit: report.xml

coverage:
  stage: test
  script:
    - echo "This is coverage test stage"
#    - coverage run -m pytest --junitxml=report.xml
    - coverage run -m pytest
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml


publishing:
  stage: publish
  # needs: [testing]
  script:
    - echo "This is the build stage"
    - poetry config repositories.gitlab https://gitlab.lrz.de/api/v4/projects/$CI_PROJECT_ID/packages/pypi
    - poetry config http-basic.gitlab gitlab-ci-token "$CI_JOB_TOKEN"
    - poetry publish -r gitlab --build
    - echo "Publishing done!"
  only:
    - main
  when: manual
