[tool.poetry]
name = "metamorphic_test"
version = "0.1.1"
description = ""
authors = ["Python Practicum TUM 2022"]

[tool.poetry.dependencies]
python = "^3.9"
hypothesis = "^6.48.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
